### ISSUE TITLE
Performance benchmarks

### ISSUE THREAD

**Issue by AriMKatz** [darrenjw/logreg#1]
Thanks for making this repo. It's a very comprehensive set of examples.

I'm particularly interested in the performance Jax vs Julia vs Dex (minus compilation time, so in Julia that would be the second run).

Will you be posting those on your blog? Can you give a sneak preview? :)

**Comment by darrenjw** [comment]
I'm deliberately not going to do a big benchmarks table, especially not for the Pima dataset, which is a bit too small to be interesting. But broadly speaking, JAX is faster than Dex, and both are much faster than Julia. Julia is not particularly fast when compared to compiled languages. eg. Scala is typically faster than Julia, despite running on the "slow" JVM.

**Comment by AriMKatz** [comment]
Gotcha. How much faster than Julia was Jax? This [PR](https://github.com/darrenjw/logreg/pull/2) brings down the Julia runtime for one of the examples by more than an order of magnitude

**Comment by darrenjw** [comment]
Yeah - this is _exactly_ why I'm _not_ going to do a big benchmarks table... It makes no sense to compare incomprehensible code written by a Julia performance tuning expert with the naive code that I've written in every other language! I think that PR probably does bring down the Julia timings closer to JAX. But the JAX code was very easy to write by a non-expert like me. I'm sure that all of the implementations in all of the languages could be tuned by experts in those languages and frameworks. That's not really the point of this exercise.

**Comment by darrenjw** [comment]
I'm not criticising your code - I'm sure it's great! But it is expert code, unlike code that would be written by a typically Bayesian statistician. This is the first Julia code that I've ever written, so it makes sense that it's not optimal. But it's also the first JAX code I've ever written, and the first Dex code I've ever written. I'm sure that those codes are also sub-optimal. Even in the languages that I'm more familiar with, I didn't put much effort into optimising. That just isn't what I'm interested in.

**Comment by kiranshila** [comment]
> Julia is not particularly fast when compared to compiled languages

This is simply not true, especially considering the fact that Julia *is* compiled.

While breaking out LoopVectorization might be a bit much to make a fair apples-to-apples comparison (not that I would consider that "expert" code) - making the implementation type stable is critically essential as per the [documentation](https://docs.julialang.org/en/v1/manual/performance-tips/). Julia isn't particularly magical, but because of the flexibility of the type system, it pays dividends to be cautious of running up against boxed operations.

All this is to say that @YingboMa's PR represents more idiomatic Julia (maybe sans the `@turbo`) and should be the point of comparison. However, I'm also interested in what parts of the PR seem like expert code and maybe what resources you used to learn Julia to see where there might be potential for improvement in documentation so newcomers to the language can have a better first impression.

**Comment by YingboMa** [comment]
> I'm not criticising your code - I'm sure it's great! But it is expert code, unlike code that would be written by a typically Bayesian statistician. This is the first Julia code that I've ever written, so it makes sense that it's not optimal. But it's also the first JAX code I've ever written, and the first Dex code I've ever written. I'm sure that those codes are also sub-optimal. Even in the languages that I'm more familiar with, I didn't put much effort into optimising. That just isn't what I'm interested in.

Thanks for the reply. I agree that due to the procedural nature of Julia, it's easy to write accidental slow code like closures. In Julia, users are excepted to use or avoid certain patterns to achieve performant code.

**Comment by ChrisRackauckas** [comment]
The code in https://github.com/darrenjw/logreg/pull/2 is about the same as what would be expected of an undergraduate in an engineering (e.g. Mechanical engineering) course by the end of week 2 (as borne out by experience). I think it's a little odd to consider every (non CS) engineering undergraduate an expert coder that Bayesian statisticians wouldn't be able to match? 

Why is it "the first code" that matters, not "one month in" or "one year in"? Surely most of the time Bayesian statisticians are not writing only a single analysis in each language and moving to the next? (By paper 10 they're using Javascript?) If the very first code someone writes is an outlier case, why is that the measure? It seems odd to see a statistician promoting that the only useful data is the outliers. This is a head scratcher 😅.

**Comment by darrenjw** [comment]
Wow. You Julia people really are as obnoxious as everyone says. Anyway, Julia was by far the least interesting of the languages considered here, so little is lost by removing it. Problem solved.
